tod:
   attachedUsbDiskCheckList[0]: E
   attachedUsbDiskCheckList[1]: F
   attachedUsbDiskCheckList[2]: G
   attachedUsbDiskCheckList[3]: H
   attachedUsbDiskCheckList[4]: I
   backupDestinationFolder: Backup\PM1000
debug: true
logging:
   level:
      billydev:
         Tools: INFO
         MyFileCopyVisitor: DEBUG

