# the following is for testing
tod:
   backupSourceFolders[0]: D:\\Temp\\\u674E\\\u658C\\\u6536\\\u85CF081226
   backupSourceFolders[1]: D:\\Temp\\11060_Exp001
   backupDestinationFolder: BackupTargetTest
   attachedUsbDiskCheckList[0]: D
   attachedUsbDiskCheckList[1]: E
   attachedUsbDiskCheckList[2]: F
   attachedUsbDiskCheckList[3]: G
   attachedUsbDiskCheckList[4]: H
   attachedUsbDiskCheckList[5]: I
